name : Terraform CI
on:
  push:
  pull_request:
permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_region: ${{ vars.TF_VAR_region }}
      TF_VAR_instance_type: ${{ vars.TF_VAR_instance_type }}
      TF_VAR_allowed_ssh_cidr: ${{ vars.TF_VAR_allowed_ssh_cidr }}
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::792192391767:role/GitHubActionsTerraformRole
          aws-region: us-east-1
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Format Check
        run:  terraform fmt -check -recursive
      - name: Terraform Init
        run:  terraform init
      - name: Terraform Validate
        run:  terraform validate
      - name: Terraform plan
        run:  terraform plan
  